use serde::{Deserialize, Serialize};

pub type Events = Vec<Event>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Event {
    pub id: String,
    pub ticker: Option<String>,
    pub slug: Option<String>,
    pub title: Option<String>,
    pub description: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub resolution_source: Option<String>,
    pub start_date: Option<String>,
    pub creation_date: Option<String>,
    pub end_date: Option<String>,
    pub image: Option<String>,
    pub icon: Option<String>,
    pub active: Option<bool>,
    pub closed: Option<bool>,
    pub archived: Option<bool>,
    pub new: Option<bool>,
    pub featured: Option<bool>,
    pub restricted: Option<bool>,
    pub liquidity: Option<f64>,
    pub volume: Option<f64>,
    pub open_interest: Option<i64>,
    pub created_at: Option<String>,
    pub updated_at: Option<String>,
    pub competitive: Option<f64>,
    #[serde(rename = "volume24hr")]
    pub volume24_hr: Option<f64>,
    #[serde(rename = "volume1wk")]
    pub volume1_wk: Option<f64>,
    #[serde(rename = "volume1mo")]
    pub volume1_mo: Option<f64>,
    #[serde(rename = "volume1yr")]
    pub volume1_yr: Option<f64>,
    pub enable_order_book: Option<bool>,
    pub liquidity_clob: Option<f64>,
    pub comment_count: Option<i64>,
    #[serde(default)]
    pub markets: Vec<Market>,
    #[serde(default)]
    pub tags: Vec<Tag>,
    pub cyom: Option<bool>,
    pub show_all_outcomes: Option<bool>,
    pub show_market_images: Option<bool>,
    pub enable_neg_risk: Option<bool>,
    pub automatically_active: Option<bool>,
    pub neg_risk_augmented: Option<bool>,
    pub pending_deployment: Option<bool>,
    pub deploying: Option<bool>,
    pub neg_risk: Option<bool>,
    #[serde(rename = "negRiskMarketID")]
    pub neg_risk_market_id: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Market {
    pub id: String,
    pub question: Option<String>,
    pub condition_id: Option<String>,
    pub slug: Option<String>,
    pub resolution_source: Option<String>,
    pub end_date: Option<String>,
    pub liquidity: Option<String>,
    pub start_date: Option<String>,
    pub image: Option<String>,
    pub icon: Option<String>,
    pub description: Option<String>,
    pub outcomes: Option<String>,
    pub outcome_prices: Option<String>,
    pub volume: Option<String>,
    pub active: Option<bool>,
    pub closed: Option<bool>,
    pub market_maker_address: Option<String>,
    pub created_at: Option<String>,
    pub updated_at: Option<String>,
    pub new: Option<bool>,
    pub featured: Option<bool>,
    pub submitted_by: Option<String>,
    pub archived: Option<bool>,
    pub resolved_by: Option<String>,
    pub restricted: Option<bool>,
    pub group_item_title: Option<String>,
    pub group_item_threshold: Option<String>,
    #[serde(rename = "questionID")]
    pub question_id: Option<String>,
    pub enable_order_book: Option<bool>,
    pub order_price_min_tick_size: Option<f64>,
    pub order_min_size: Option<i64>,
    pub volume_num: Option<f64>,
    pub liquidity_num: Option<f64>,
    pub end_date_iso: Option<String>,
    pub start_date_iso: Option<String>,
    pub has_reviewed_dates: Option<bool>,
    #[serde(rename = "volume24hr")]
    pub volume24_hr: Option<f64>,
    #[serde(rename = "volume1wk")]
    pub volume1_wk: Option<f64>,
    #[serde(rename = "volume1mo")]
    pub volume1_mo: Option<f64>,
    #[serde(rename = "volume1yr")]
    pub volume1_yr: Option<f64>,
    pub clob_token_ids: Option<String>,
    pub uma_bond: Option<String>,
    pub uma_reward: Option<String>,
    #[serde(rename = "volume24hrClob")]
    pub volume24_hr_clob: Option<f64>,
    #[serde(rename = "volume1wkClob")]
    pub volume1_wk_clob: Option<f64>,
    #[serde(rename = "volume1moClob")]
    pub volume1_mo_clob: Option<f64>,
    #[serde(rename = "volume1yrClob")]
    pub volume1_yr_clob: Option<f64>,
    pub volume_clob: Option<f64>,
    pub liquidity_clob: Option<f64>,
    pub custom_liveness: Option<i64>,
    pub accepting_orders: Option<bool>,
    pub neg_risk: Option<bool>,
    #[serde(rename = "negRiskRequestID")]
    pub neg_risk_request_id: Option<String>,
    pub ready: Option<bool>,
    pub funded: Option<bool>,
    pub accepting_orders_timestamp: Option<String>,
    pub cyom: Option<bool>,
    pub competitive: Option<f64>,
    pub pager_duty_notification_enabled: Option<bool>,
    pub approved: Option<bool>,
    pub rewards_min_size: Option<i64>,
    pub rewards_max_spread: Option<f64>,
    pub spread: Option<f64>,
    pub one_day_price_change: Option<f64>,
    pub one_hour_price_change: Option<f64>,
    pub one_week_price_change: Option<f64>,
    pub one_month_price_change: Option<f64>,
    pub last_trade_price: Option<f64>,
    pub best_bid: Option<f64>,
    pub best_ask: Option<f64>,
    pub automatically_active: Option<bool>,
    pub clear_book_on_start: Option<bool>,
    pub manual_activation: Option<bool>,
    pub neg_risk_other: Option<bool>,
    pub uma_resolution_statuses: Option<String>,
    pub pending_deployment: Option<bool>,
    pub deploying: Option<bool>,
    pub deploying_timestamp: Option<String>,
    pub rfq_enabled: Option<bool>,
    pub holding_rewards_enabled: Option<bool>,
    pub fees_enabled: Option<bool>,
    pub closed_time: Option<String>,
    pub uma_end_date: Option<String>,
    pub uma_resolution_status: Option<String>,
    pub automatically_resolved: Option<bool>,
    #[serde(rename = "negRiskMarketID")]
    pub neg_risk_market_id: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Tag {
    pub id: Option<String>,
    pub label: Option<String>,
    pub slug: Option<String>,
    pub force_show: Option<bool>,
    pub published_at: Option<String>,
    pub created_at: Option<String>,
    pub updated_at: Option<String>,
    pub updated_by: Option<i64>,
    pub force_hide: Option<bool>,
    pub is_carousel: Option<bool>,
    pub created_by: Option<i64>,
}
